spring.application.name=BaiTap8

# Bật giao diện kiểm thử GraphiQL tại http://localhost:8080/graphiql
spring.graphql.graphiql.enabled=true

# Cấu hình Database H2 lưu trên bộ nhớ RAM
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
