spring.application.name=BaiTap10
server.port=8005

# ===============================
# CẤU HÌNH KẾT NỐI DATABASE (SQL SERVER SQLEXPRESS01)
# ===============================
spring.datasource.url=jdbc:sqlserver://localhost:56003;databaseName=jwt_springboot3;encrypt=false;trustServerCertificate=true;sendStringParametersAsUnicode=true
spring.datasource.username=sa
spring.datasource.password=giahan
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# ===============================
# JPA / HIBERNATE CONFIGURATION
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# CẤU HÌNH BẢO MẬT NIMBUS JWT
# ===============================
# Chuỗi secret key bảo mật 256 bits cho HS256
security.jwt.secret-key=3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
# Thời hạn hiệu lực Token (1 giờ = 3600000 ms)
security.jwt.expiration-time=3600000

# ===============================
# THYMELEAF CONFIGURATION
# ===============================
spring.thymeleaf.cache=false
